#!/usr/bin/env bash

set -x
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

PROJECT_DIR="$DIR"

# Allow CI to override via environment; fall back to the local Xcode 14.3.1 path.
XCODE_DEVELOPER_DIR="${XCODE_DEVELOPER_DIR:-Fill Me IN}"
XCODEBUILD="$XCODE_DEVELOPER_DIR/usr/bin/xcodebuild"

# Assert xcode-select points at Xcode 14.3.1.
# xcodebuild's modern build daemon uses xcode-select — not DEVELOPER_DIR —
# to locate its compiler toolchain.  Using the wrong Xcode produces a
# mismatched VFS stat cache and "stdio.h not found" failures.
ACTIVE_XCODE=$(xcode-select -p 2>/dev/null)
if [ "$ACTIVE_XCODE" != "$XCODE_DEVELOPER_DIR" ]; then
  echo "ERROR: xcode-select is pointing at:"
  echo "  $ACTIVE_XCODE"
  echo "This build requires Xcode 14.3.1 at:"
  echo "  $XCODE_DEVELOPER_DIR"
  echo "Fix with: sudo xcode-select -s ${XCODE_DEVELOPER_DIR%/Contents/Developer}"
  exit 1
fi

# Run the JDK configure+make with the system (macOS) clang.
# DEVELOPER_DIR must NOT point to the iOS Xcode here — adlc and other
# host build tools need to link against macOS libs, not iOS libs.
# Unset iOS env vars that may be active from .envrc/direnv.
cd $PROJECT_DIR/labs-openjdk/labs-openjdk-21

echo "Building OpenJDK 21 with GraalVM ..."
env -u DEVELOPER_DIR -u CC -u CXX -u CFLAGS -u CXXFLAGS -u LDFLAGS -u SDKROOT -u ARCHFLAGS -u SYSROOT ./build.sh

# xcodebuild steps require the active Xcode with an iOS SDK.
# -UseModernBuildSystem=NO forces the legacy build system, which invokes
# clang directly from DT_TOOLCHAIN_DIR rather than through the build daemon.
export DEVELOPER_DIR="$XCODE_DEVELOPER_DIR"

# Explicitly set the compiler from the active Xcode toolchain.
# Even with DEVELOPER_DIR and xcode-select pinned, xcodebuild can still
# resolve DT_TOOLCHAIN_DIR to the system Xcode (/Applications/Xcode.app).
# Passing CC/CXX directly on the command line overrides all toolchain resolution.
XCODE_CLANG="$XCODE_DEVELOPER_DIR/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"

# Delete all stale VFS stat caches — may have been generated by a different
# Xcode version.  xcodebuild passes -ivfsstatcache to clang; a cache built by
# a different Xcode causes "stdio.h not found" even when the SDK path is correct.
rm -f ~/Library/Developer/Xcode/DerivedData/SDKStatCaches.noindex/iphoneos*.sdkstatcache

echo "Building libjava.a ..."
cd $PROJECT_DIR/labs-openjdk
"$XCODEBUILD" -scheme libjava -sdk iphoneos -configuration Release-ios \
    -UseModernBuildSystem=NO \
    CC="$XCODE_CLANG" \
    CXX="${XCODE_CLANG}++"

echo "Building libjvm.a ..."
cd $PROJECT_DIR/svm
"$XCODEBUILD" -scheme libjvm -sdk iphoneos -configuration Release-ios \
    -UseModernBuildSystem=NO \
    CC="$XCODE_CLANG" \
    CXX="${XCODE_CLANG}++"

cd $PROJECT_DIR
mkdir -p build/ios-arm64/{lib,static}

echo "Copying built libs to build/ios-arm64/lib ..."
cd $PROJECT_DIR/build/ios-arm64/lib
cp $PROJECT_DIR/svm/build/xcode/Release-ios-iphoneos/libjvm.a .
cp $PROJECT_DIR/labs-openjdk/build/xcode/Release-ios-iphoneos/libjava.a .

echo "Copying static libs to build/ios-arm64/static ..."
cd $PROJECT_DIR/build/ios-arm64/static
# These come from 'make static-libs-image' which uses the macOS SDK (not iOS).
# Pure-POSIX libs (libzip, libprefs, libj2pkcs11, libjaas, etc.) are arm64
# machine code with no macOS-specific API calls, so they are ABI-compatible
# with iOS arm64 at the linker level.
# NOTE: do NOT link libnet.a / libnio.a / libjava.a from here — use
# build/ios-arm64/lib/libjava.a (iOS-targeted, built by svm.openjdk.xcodeproj)
# to avoid duplicate symbols.
cp $PROJECT_DIR/labs-openjdk/labs-openjdk-21/build/labsjdk/images/static-libs/lib/*.a .
